### ISSUE TITLE
Update checklist birds 2024

### ISSUE THREAD

**Issue by sannegovaert** [trias-project/alien-birds-checklist#19]
We will release a new publication. I moved the data from the [old spreadsheet](https://docs.google.com/spreadsheets/d/1ugsmAq_tlUjFmZef2zyw-mT0Tq1jSdPlNO4KTfJyXVo/edit#gid=0) to the new big spreadsheet with all checklists together, so it is easier to manage. Can you check wether the [current checklist](https://docs.google.com/spreadsheets/d/1LeXXbry2ArK2rngsmFjz_xErwE1KwQ8ujtvHNmTVA6E/edit#gid=1556976278) is up to date?

Most important is to check:
- [ ] In the old checklist, row 212 - 245 are marked in red. What is the meaning of this, and is it still relevant?
- [ ] In the old checklist, there are several tabs, e.g. `removed` and `not included`. I did not copy those to the new spreadsheet. Check if this is ok. See #2 
- [ ] Is it correct that the line with Poephila guttata can be deleted? See #15 
- [ ] add the species that were introduced since the last publication
- [ ] There is many missing data. Please fill in as much as possible, especially for `degree of establishment`, `introduction pathway`, `date first observation` (see #11, but this counts for all species) , `date last observation` and `source`. 
- [ ] clean up `source`, see #6. The original source of an observation cannot be the unified checklist. The original source is a publication, unpublished observation, or an observation that has a link (e.g. a specific link to observation.org).
- [ ] Make sure all data is correct/updated.

**Comment by DiederikStrubbe** [comment]
Hi, is there a difference between the 'source' and 'source original' column?

**Comment by sannegovaert** [comment]
> Hi, is there a difference between the 'source' and 'source original' column?

`source` is used in the publication. `source original` is probably only for internal check? @timadriaens

**Comment by DiederikStrubbe** [comment]
African fish eagle Haliaeetus vocifer (Daudin, 1800) has been changed to Icthyophaga vocifer (Daudin, 1800). Do I just change that in the table?

**Comment by sannegovaert** [comment]
On GBIF, both species names are linked to each other, so you can change it in the table. Currently, GBIF takes [Haliaeetus vocifer (Daudin, 1800)](https://www.gbif.org/species/2480454) as accepted name and [Icthyophaga vocifer (Daudin, 1800)](https://www.gbif.org/species/12326430) as homotypic synonym. This means that on our list it will be Icthyophaga but on GBIF it will still be Haliaeetus. Probably this will be updated but just takes some time.

For all species currently in the spreadsheet, there is a unique taxonID hash in hidden column A. So when you change the name (assuming it is only a name change and not a species change), the ID will stay the same.

**Comment by DiederikStrubbe** [comment]
OK thanks - so I can change it but in fact not really needed as it is taken
into account later anhow.

D

Op vr 21 jun 2024 om 09:43 schreef Sanne Govaert ***@***.***>:

**Comment by LienReyserhove** [comment]
It's taken into account, but it's good practice that the expert uses the scientific name that he/she believes is correct and up to date. So I would suggest to change `Haliaeetus vocifer (Daudin, 1800)` to `Icthyophaga vocifer (Daudin, 1800)` in the source checklist.

**Comment by DiederikStrubbe** [comment]
Thanks, I will.

Op vr 21 jun 2024 om 11:17 schreef Lien Reyserhove ***@***.***
